// This file is auto-generated by scripts/generate-env.js
// Do not edit manually.

package im.cxa.fanatter

internal object EnvSecrets {
  private data class Obfuscated(
    val length: Int,
    val cipherEven: IntArray,
    val cipherOdd: IntArray,
    val maskEven: IntArray,
    val maskOdd: IntArray,
  )

  private fun decode(data: Obfuscated): String {
    val chars = CharArray(data.length)
    for (i in 0 until data.length) {
      val even = i % 2 == 0
      val cipher = if (even) data.cipherEven[i / 2] else data.cipherOdd[i / 2]
      val mask = if (even) data.maskEven[i / 2] else data.maskOdd[i / 2]
      chars[i] = (cipher xor mask).toChar()
    }
    return String(chars)
  }

  private val consumerKeyData = Obfuscated(
    length = 32,
    cipherEven = intArrayOf(146, 157, 32, 205, 211, 49, 156, 27, 176, 71, 243, 212, 96, 157, 225, 127),
    cipherOdd = intArrayOf(50, 106, 36, 49, 222, 136, 161, 94, 149, 181, 31, 56, 220, 100, 5, 248),
    maskEven = intArrayOf(170, 171, 67, 174, 182, 4, 254, 46, 128, 35, 145, 181, 84, 171, 208, 73),
    maskOdd = intArrayOf(80, 82, 20, 4, 188, 187, 152, 107, 161, 211, 43, 0, 237, 92, 52, 153),
  )

  private val consumerSecretData = Obfuscated(
    length = 32,
    cipherEven = intArrayOf(5, 231, 119, 215, 171, 13, 54, 216, 48, 203, 178, 150, 92, 251, 79, 244),
    cipherOdd = intArrayOf(164, 10, 3, 57, 17, 118, 81, 246, 239, 174, 47, 154, 41, 220, 126, 218),
    maskEven = intArrayOf(50, 210, 66, 239, 156, 111, 7, 189, 83, 253, 211, 244, 109, 200, 46, 196),
    maskOdd = intArrayOf(145, 51, 59, 95, 114, 79, 53, 149, 216, 200, 29, 169, 27, 233, 29, 184),
  )

  fun consumerKey(): String = decode(consumerKeyData)
  fun consumerSecret(): String = decode(consumerSecretData)
}
