// This file is auto-generated by scripts/generate-env.js
// Do not edit manually.

package im.cxa.fanatter

internal object EnvSecrets {
  private data class Obfuscated(
    val length: Int,
    val cipherEven: IntArray,
    val cipherOdd: IntArray,
    val maskEven: IntArray,
    val maskOdd: IntArray,
  )

  private fun decode(data: Obfuscated): String {
    val chars = CharArray(data.length)
    for (i in 0 until data.length) {
      val even = i % 2 == 0
      val cipher = if (even) data.cipherEven[i / 2] else data.cipherOdd[i / 2]
      val mask = if (even) data.maskEven[i / 2] else data.maskOdd[i / 2]
      chars[i] = (cipher xor mask).toChar()
    }
    return String(chars)
  }

  private val consumerKeyData = Obfuscated(
    length = 32,
    cipherEven = intArrayOf(6, 136, 118, 205, 132, 225, 120, 189, 226, 180, 246, 109, 105, 239, 109, 32),
    cipherOdd = intArrayOf(79, 4, 59, 70, 109, 129, 227, 181, 142, 35, 180, 46, 182, 223, 243, 123),
    maskEven = intArrayOf(62, 190, 21, 174, 225, 212, 26, 136, 210, 208, 148, 12, 93, 217, 92, 22),
    maskOdd = intArrayOf(45, 60, 11, 115, 15, 178, 218, 128, 186, 69, 128, 22, 135, 231, 194, 26),
  )

  private val consumerSecretData = Obfuscated(
    length = 32,
    cipherEven = intArrayOf(123, 34, 251, 17, 96, 119, 211, 244, 190, 223, 25, 87, 78, 32, 181, 249),
    cipherOdd = intArrayOf(2, 204, 232, 109, 73, 201, 2, 24, 36, 97, 60, 48, 189, 189, 212, 197),
    maskEven = intArrayOf(76, 23, 206, 41, 87, 21, 226, 145, 221, 233, 120, 53, 127, 19, 212, 201),
    maskOdd = intArrayOf(55, 245, 208, 11, 42, 240, 102, 123, 19, 7, 14, 3, 143, 136, 183, 167),
  )

  fun consumerKey(): String = decode(consumerKeyData)
  fun consumerSecret(): String = decode(consumerSecretData)
}
