// This file is auto-generated by scripts/generate-env.js
// Do not edit manually.

package im.cxa.fanatter

internal object EnvSecrets {
  private data class Obfuscated(
    val length: Int,
    val cipherEven: IntArray,
    val cipherOdd: IntArray,
    val maskEven: IntArray,
    val maskOdd: IntArray,
  )

  private fun decode(data: Obfuscated): String {
    val chars = CharArray(data.length)
    for (i in 0 until data.length) {
      val even = i % 2 == 0
      val cipher = if (even) data.cipherEven[i / 2] else data.cipherOdd[i / 2]
      val mask = if (even) data.maskEven[i / 2] else data.maskOdd[i / 2]
      chars[i] = (cipher xor mask).toChar()
    }
    return String(chars)
  }

  private val consumerKeyData = Obfuscated(
    length = 32,
    cipherEven = intArrayOf(245, 206, 51, 255, 178, 23, 170, 166, 186, 8, 71, 43, 119, 214, 141, 11),
    cipherOdd = intArrayOf(57, 159, 77, 91, 12, 79, 0, 8, 165, 56, 113, 107, 50, 180, 58, 38),
    maskEven = intArrayOf(205, 248, 80, 156, 215, 34, 200, 147, 138, 108, 37, 74, 67, 224, 188, 61),
    maskOdd = intArrayOf(91, 167, 125, 110, 110, 124, 57, 61, 145, 94, 69, 83, 3, 140, 11, 71),
  )

  private val consumerSecretData = Obfuscated(
    length = 32,
    cipherEven = intArrayOf(168, 235, 238, 36, 122, 102, 137, 213, 241, 151, 151, 240, 62, 135, 14, 77),
    cipherOdd = intArrayOf(117, 216, 254, 89, 28, 150, 202, 113, 181, 83, 216, 163, 119, 186, 211, 194),
    maskEven = intArrayOf(159, 222, 219, 28, 77, 4, 184, 176, 146, 161, 246, 146, 15, 180, 111, 125),
    maskOdd = intArrayOf(64, 225, 198, 63, 127, 175, 174, 18, 130, 53, 234, 144, 69, 143, 176, 160),
  )

  fun consumerKey(): String = decode(consumerKeyData)
  fun consumerSecret(): String = decode(consumerSecretData)
}
